DB_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?user=postgres.qjbvuxwrrxssvfezpsyw&password=B202378459AM&sslmode=require
DB_USER=postgres.qjbvuxwrrxssvfezpsyw
DB_PASSWORD=B202378459AM
